"""Export a checkpoint to the Game Boy ROM sources.

    python -m llm.export models/tiny/ckpt.pt [--out gb/gen] [--json models/tiny/model_int.json]

Generated files (all overwritten):
    gb/gen/model_config.h     dimensions and fixed-point constants
    gb/gen/model_weights.h    extern declarations + descriptor tables
    gb/gen/model_desc.c       bank-0 descriptor tables (pointers + bank numbers)
    gb/gen/model_bank_N.c     weight matrices, one file per 16 KiB ROM bank
    gb/gen/dot_gen.s          unrolled SM83 table-lookup dot product + SQ table
    gb/gen/model.mk           Makefile fragment (RAM size, model name)
"""
import argparse
import os
import shutil

import numpy as np

from . import quant as Q
from .tokenizer import VOCAB_SIZE, c_vocab_table, VOCAB
from .intmodel import extract, save_json, summary

BANK_BYTES = 16 * 1024
BANK_RESERVE = 64          # keep a little slack per bank
SQ_TABLE_ADDR = 0x3E00     # page-aligned, top of ROM bank 0 (256 B lo + 256 B hi)
ENTRY_STEP = 16


def c_array(name, ctype, values, per_line=24, static=False, extra_attr=""):
    vals = [str(int(v)) for v in values]
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(vals[i:i + per_line]) + ",")
    body = "\n".join(lines)
    prefix = "static " if static else ""
    return f"{prefix}const {ctype} {name}[{len(vals)}]{extra_attr} = {{\n{body}\n}};\n"


class BankPacker:
    """Greedy first-fit packing of const blobs into 16 KiB switchable ROM banks (1..N)."""

    def __init__(self):
        self.banks = []   # list of [used_bytes, [chunks]]

    def add(self, name, code, nbytes):
        for i, b in enumerate(self.banks):
            if b[0] + nbytes <= BANK_BYTES - BANK_RESERVE:
                b[0] += nbytes
                b[1].append((name, code))
                return i + 1
        assert nbytes <= BANK_BYTES - BANK_RESERVE, f"{name} ({nbytes} B) does not fit in one ROM bank"
        self.banks.append([nbytes, [(name, code)]])
        return len(self.banks)


def gen_matrix(name, w):
    """int7 matrix (rows x cols) -> biased bytes + per-row sum of squares."""
    w = np.asarray(w, dtype=np.int64)
    assert w.min() >= -Q.QMAX and w.max() <= Q.QMAX
    biased = (w + Q.BIAS).astype(np.int64).flatten()
    sq = (w * w).sum(axis=1)
    code = c_array(name, "uint8_t", biased) + c_array(name + "_sq", "uint32_t", sq, per_line=12)
    nbytes = biased.size + 4 * sq.size
    return code, nbytes


def gen_dot_asm(nmax):
    """Unrolled dot product with an entry point every ENTRY_STEP elements."""
    out = []
    out.append("; Generated by llm/export.py - do not edit.\n")
    out.append("; S = sum over i in [entry, NMAX) of SQ[w_i + xvec_i]  (biased int7 bytes)\n")
    out.append("; in : _dot_ptr = address of the weight row (any readable memory, current banks)\n")
    out.append("; out: _dot_acc = S (uint32)\n")
    out.append("        .area _DATA\n_dot_spsave: .ds 2\n")
    out.append("        .area _CODE\n")
    out.append("        .globl _xvec\n        .globl _dot_ptr\n        .globl _dot_acc\n")
    entries = list(range(0, nmax, ENTRY_STEP))
    for e in entries:
        out.append(f"        .globl _dot_from_{e}\n")
    # entry stubs: save SP, point SP at the weight row, clear the 24-bit accumulator (d:hl)
    for e in entries:
        out.append(f"_dot_from_{e}::\n"
                   "        di\n"
                   "        ld (_dot_spsave),sp\n"
                   "        ld a,(_dot_ptr)\n"
                   "        ld l,a\n"
                   "        ld a,(_dot_ptr+1)\n"
                   "        ld h,a\n"
                   "        ld sp,hl\n"
                   "        ld hl,#0\n"
                   "        ld d,#0\n"
                   f"        jp dot_u{e}\n")
    lbl = 0
    for i in range(0, nmax, 2):
        if i % ENTRY_STEP == 0:
            out.append(f"dot_u{i}:\n")
        lbl += 1
        out.append(
            "        pop bc\n"
            "        ld e,b\n"
            f"        ld a,(_xvec+{i})\n"
            "        add a,c\n"
            "        ld c,a\n"
            "        ld b,#>_sq_tbl\n"
            "        ld a,(bc)\n"
            "        add a,l\n"
            "        ld l,a\n"
            "        inc b\n"
            "        ld a,(bc)\n"
            "        adc a,h\n"
            "        ld h,a\n"
            f"        jr nc,{lbl}$\n"
            "        inc d\n"
            f"{lbl}$:\n")
        lbl += 1
        out.append(
            f"        ld a,(_xvec+{i + 1})\n"
            "        add a,e\n"
            "        ld c,a\n"
            "        dec b\n"
            "        ld a,(bc)\n"
            "        add a,l\n"
            "        ld l,a\n"
            "        inc b\n"
            "        ld a,(bc)\n"
            "        adc a,h\n"
            "        ld h,a\n"
            f"        jr nc,{lbl}$\n"
            "        inc d\n"
            f"{lbl}$:\n")
    out.append(
        "dot_done:\n"
        "        ld a,l\n"
        "        ld (_dot_acc),a\n"
        "        ld a,h\n"
        "        ld (_dot_acc+1),a\n"
        "        ld a,d\n"
        "        ld (_dot_acc+2),a\n"
        "        xor a\n"
        "        ld (_dot_acc+3),a\n"
        "        ld a,(_dot_spsave)\n"
        "        ld l,a\n"
        "        ld a,(_dot_spsave+1)\n"
        "        ld h,a\n"
        "        ld sp,hl\n"
        "        ei\n"
        "        ret\n")
    # SQ table: page 0 = low bytes, page 1 = high bytes, at a fixed page-aligned ROM address
    sq = Q.sq_table()
    out.append(f"        .area _SQTBL (ABS)\n        .org 0x{SQ_TABLE_ADDR:04X}\n_sq_tbl::\n")
    for page in (0, 1):
        vals = [(v >> (8 * page)) & 0xFF for v in sq]
        for i in range(0, 256, 16):
            out.append("        .db " + ",".join(str(v) for v in vals[i:i + 16]) + "\n")
    return "".join(out)


def export(m: dict, out_dir: str):
    cfg = m["config"]
    D, H, F, T, L, V = cfg["d_model"], cfg["n_heads"], cfg["d_ff"], cfg["ctx"], cfg["n_layers"], cfg["vocab_size"]
    nmax = max(D, F, T)
    assert nmax % ENTRY_STEP == 0
    if os.path.isdir(out_dir):
        for f in os.listdir(out_dir):
            if f.startswith("model_") or f == "dot_gen.s":
                os.remove(os.path.join(out_dir, f))
    os.makedirs(out_dir, exist_ok=True)

    packer = BankPacker()
    mats = {}   # name -> bank

    def add_mat(name, w):
        code, n = gen_matrix(name, w)
        mats[name] = packer.add(name, code, n)

    for l, ly in enumerate(m["layers"]):
        for k in ("wq", "wk", "wv", "wo", "w1", "w2"):
            add_mat(f"L{l}_{k}", ly[k])
    add_mat("lm_head", m["lm_head"])
    tok = np.asarray(m["tok_emb"]).flatten()
    pos = np.asarray(m["pos_emb"]).flatten()
    mats["tok_emb"] = packer.add("tok_emb", c_array("tok_emb", "int8_t", tok), tok.size)
    mats["pos_emb"] = packer.add("pos_emb", c_array("pos_emb", "int8_t", pos), pos.size)

    # ---- bank files
    for i, (used, chunks) in enumerate(packer.banks):
        bank = i + 1
        with open(os.path.join(out_dir, f"model_bank_{bank}.c"), "w") as f:
            f.write(f"/* Generated by llm/export.py - ROM bank {bank}, {used} bytes used. Do not edit. */\n")
            f.write("#include <stdint.h>\n")
            f.write(f"#pragma bank {bank}\n\n")
            for name, code in chunks:
                f.write(code + "\n")

    # ---- header
    ram_banks = 2 * L
    # makebin -ya takes the number of 8 KiB SRAM banks (1, 4, 8 or 16 -> header codes 02, 03, 05, 04)
    ram_code = 1 if ram_banks <= 1 else 4 if ram_banks <= 4 else 8 if ram_banks <= 8 else 16
    assert ram_banks <= 16, "at most 8 layers (16 SRAM banks of 8 KiB)"
    assert T * D + T * H * 2 <= 8192, "K cache + row sums must fit one 8 KiB SRAM bank"
    assert D * T + D * 4 + D * 2 <= 8192, "V cache + sums must fit one 8 KiB SRAM bank"
    with open(os.path.join(out_dir, "model_config.h"), "w") as f:
        f.write("/* Generated by llm/export.py - do not edit. */\n#ifndef MODEL_CONFIG_H\n#define MODEL_CONFIG_H\n\n")
        f.write(f'#define M_NAME "{cfg["name"]}"\n')
        f.write(f"#define M_D {D}\n#define M_H {H}\n#define M_HD {D // H}\n#define M_F {F}\n#define M_T {T}\n")
        f.write(f"#define M_L {L}\n#define M_V {V}\n#define M_NMAX {nmax}\n")
        f.write(f"#define M_QMAX {Q.QMAX}\n#define M_BIAS {Q.BIAS}\n")
        f.write(f"#define M_E_RES {m['e_res']}\n#define M_TOK_SHIFT {m['e_res'] - m['e_tok']}\n#define M_POS_SHIFT {m['e_res'] - m['e_pos']}\n")
        f.write(f"#define M_NORM_K {m['norm_k']}UL\n#define M_NORM_K_BITS {Q.NORM_K_BITS}\n")
        assert m["lm_shift"] == Q.SCALE_SHIFT and all(ly["att_shift"] == Q.SCALE_SHIFT for ly in m["layers"])
        f.write(f"#define M_LM_MUL {m['lm_mul']}\n#define M_SCALE_SHIFT {Q.SCALE_SHIFT}\n")
        f.write(f"#define M_EXP_MAX {Q.EXP_MAX}\n#define M_MAX_LOGIT_DIFF {Q.MAX_LOGIT_DIFF}L\n")
        f.write(f"#define M_RAM_BANKS {ram_banks}\n#define M_ROM_BANKS {len(packer.banks) + 1}\n")
        f.write(f"#define M_VOCAB_CHARS {c_vocab_table()}\n")
        f.write(f"#define TOK_PAD 0\n#define TOK_EOS 1\n#define TOK_USR 2\n#define TOK_BOT 3\n")
        f.write("\n#endif\n")

    # ---- descriptors (bank 0) and extern declarations
    with open(os.path.join(out_dir, "model_weights.h"), "w") as f:
        f.write("/* Generated by llm/export.py - do not edit. */\n#ifndef MODEL_WEIGHTS_H\n#define MODEL_WEIGHTS_H\n")
        f.write("#include <stdint.h>\n#include \"model_config.h\"\n\n")
        f.write("typedef struct { const uint8_t *w; const uint32_t *sq; uint8_t bank; } mat_t;\n")
        f.write("typedef struct {\n    uint8_t s_q, s_k, s_v, s_ao, rs_a, s_f, s_fo, rs_f;\n"
                "    uint16_t att_mul;\n} layer_cfg_t;\n\n")
        for name in mats:
            if name in ("tok_emb", "pos_emb"):
                f.write(f"extern const int8_t {name}[];\n")
            else:
                f.write(f"extern const uint8_t {name}[];\nextern const uint32_t {name}_sq[];\n")
        f.write("\nextern const mat_t mat_wq[M_L], mat_wk[M_L], mat_wv[M_L], mat_wo[M_L], mat_w1[M_L], mat_w2[M_L];\n")
        f.write("extern const mat_t mat_lm;\nextern const layer_cfg_t layer_cfg[M_L];\n")
        f.write(f"#define TOK_EMB_BANK {mats['tok_emb']}\n#define POS_EMB_BANK {mats['pos_emb']}\n")
        f.write("typedef void (*dotfn_t)(void);\nextern const dotfn_t dot_entries[M_NMAX / 16];\n")
        for e in range(0, nmax, ENTRY_STEP):
            f.write(f"void dot_from_{e}(void);\n")
        f.write("\n#endif\n")

    with open(os.path.join(out_dir, "model_desc.c"), "w") as f:
        f.write("/* Generated by llm/export.py - bank 0 descriptor tables. Do not edit. */\n")
        f.write("#include \"model_weights.h\"\n\n")
        for k in ("wq", "wk", "wv", "wo", "w1", "w2"):
            f.write(f"const mat_t mat_{k}[M_L] = {{\n")
            for l in range(L):
                n = f"L{l}_{k}"
                f.write(f"    {{ {n}, {n}_sq, {mats[n]} }},\n")
            f.write("};\n")
        f.write(f"const mat_t mat_lm = {{ lm_head, lm_head_sq, {mats['lm_head']} }};\n\n")
        f.write("const layer_cfg_t layer_cfg[M_L] = {\n")
        for ly in m["layers"]:
            f.write(f"    {{ {ly['s_q']}, {ly['s_k']}, {ly['s_v']}, {ly['s_ao']}, {ly['rs_a']}, "
                    f"{ly['s_f']}, {ly['s_fo']}, {ly['rs_f']}, {ly['att_mul']} }},\n")
        f.write("};\n\n")
        f.write("const dotfn_t dot_entries[M_NMAX / 16] = {\n    " +
                ", ".join(f"dot_from_{e}" for e in range(0, nmax, ENTRY_STEP)) + "\n};\n")

    with open(os.path.join(out_dir, "dot_gen.s"), "w") as f:
        f.write(gen_dot_asm(nmax))

    with open(os.path.join(out_dir, "model.mk"), "w") as f:
        f.write("# Generated by llm/export.py - do not edit.\n")
        f.write(f"MODEL_NAME = {cfg['name']}\n")
        f.write(f"RAM_BANKS = {ram_code}\n")
        f.write(f"ROM_BANKS = {len(packer.banks) + 1}\n")

    return {"rom_banks": len(packer.banks) + 1, "ram_code": ram_code, "banks": [b[0] for b in packer.banks]}


def main():
    ap = argparse.ArgumentParser(description="export a checkpoint to Game Boy C sources")
    ap.add_argument("checkpoint")
    ap.add_argument("--out", default="gb/gen")
    ap.add_argument("--json", default=None, help="also write the integer model as JSON (default: next to the checkpoint)")
    args = ap.parse_args()
    from .model import load_checkpoint
    model, _ = load_checkpoint(args.checkpoint)
    m = extract(model)
    print(summary(m))
    info = export(m, args.out)
    json_path = args.json or os.path.join(os.path.dirname(args.checkpoint) or ".", "model_int.json")
    save_json(m, json_path)
    print(f"wrote {args.out}/ (ROM banks: {info['rom_banks']}, bank usage: {info['banks']}, SRAM banks {info['ram_code']})")
    print(f"wrote {json_path}")


if __name__ == "__main__":
    main()
