/* Generated by tools/fontgen.py - do not edit. */
#ifndef FONT_H
#define FONT_H
#include <stdint.h>
#define FONT_NGLYPHS 57
#define FONT_NTILES 114
#define FONT_INV_OFFSET 57
extern const uint8_t font_tiles[];
extern const uint8_t font_map[128];
#define CHAR_TILE(c) (font_map[(uint8_t)(c) & 0x7F])
#endif
